#application.properties，application.yml，application.yaml的作用都一样
#但是.yml和.yaml更加结构化，而且他们俩完全一样，只有后缀名有小不同
#application.properties的优先级高于application.yml，application.yaml，即同时存在的时候优先使用application.properties

server:
  port: 8080
  servlet:
    context-path: /springboot
